export const themes = {
  carSpace: {
    background: "carSpaceThemeBackground",
    hr: "carSpaceThemeHr",
    serviceLogs: "carSpaceThemeServiceLogs",
    vehicleItemList: "carSpaceThemeVehicleItemList",
    vehicleItemListFont: "carSpaceThemeVehicleItemListFont",
    oneUpdate: "carSpaceThemeOneUpdate",
    redText: "",
    accountDetails: "carSpaceThemeAccountDetails",
  },
  light: {
    background: "lightThemeBackground",
    hr: "lightThemeHr",
    serviceLogs: "lightThemeServiceLogs",
    vehicleItemList: "lightThemeVehicleItemList",
    vehicleItemListFont: "lightThemeVehicleItemListFont",
    oneUpdate: "lightThemeOneUpdate",
    redText: "",
    accountDetails: "lightThemeAccountDetails",
  },
  grey: {
    background: "greyThemeBackground",
    hr: "greyThemeHr",
    serviceLogs: "greyThemeServiceLogs",
    vehicleItemList: "greyThemeVehicleItemList",
    vehicleItemListFont: "greyThemeVehicleItemListFont",
    oneUpdate: "greyThemeOneUpdate",
    redText: "greyThemeRedText",
    accountDetails: "greyThemeAccountDetails",
  },
  dark: {
    background: "darkThemeBackground",
    hr: "darkThemeHr",
    serviceLogs: "darkThemeServiceLogs",
    vehicleItemList: "darkThemeVehicleItemList",
    vehicleItemListFont: "darkThemeVehicleItemListFont",
    oneUpdate: "darkThemeOneUpdate",
    redText: "darkThemeRedText",
    accountDetails: "darkThemeAccountDetails",
  },
};
